[default.extend-words]
astroid = "astroid"

nd = "nd"
BA = "BA"
ba = "ba"
brach = "brach"
ABD = "ABD"
DNE = "DNE"

Hass = "Hass"
Strang = "Strang"

multline = "multline"

infiniment = "infiniment"

typ = "typ"
Comput = "Comput"
