<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Calculus with Julia - 45&nbsp; Volumes by slicing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../integrals/arc_length.html" rel="next">
<link href="../integrals/center_of_mass.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Calculus with Julia</span>
    </a>
  </div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Volumes by slicing</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../precalc.html" class="sidebar-item-text sidebar-link">Precalculus Concepts</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/calculator.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">From calculator to computer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/numbers_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Number systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/logical_expressions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inequalities, Logical expressions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/ranges.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Ranges and Sets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Graph of a Function</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/transformations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Function manipulations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/inversefunctions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Inverse of a Function</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/polynomial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Polynomials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/polynomial_roots.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Roots of a polynomial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/polynomials_package.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Polynomials package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/rational_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Rational functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/exp_log_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Exponential and logarithmic functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/trig_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Trigonometric functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../precalc/julia_overview.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Overview of Julia commands</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../limits.html" class="sidebar-item-text sidebar-link">Limits</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../limits/limits.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Limits</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../limits/limits_extensions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Limits, issues, extensions of the concept</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../limits/continuity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Continuity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../limits/intermediate_value_theorem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Implications of continuity</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../derivatives.html" class="sidebar-item-text sidebar-link">Derivatives</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/derivatives.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/numeric_derivatives.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Numeric derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/symbolic_derivatives.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Symbolic derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/mean_value_theorem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">The mean value theorem for differentiable functions.</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Optimization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/first_second_derivatives.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">The first and second derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/curve_sketching.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Curve Sketching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/linearization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Linearization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/newtons_method.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Newton’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/more_zeros.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Derivative-free alternatives to Newton’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/lhospitals_rule.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">L’Hospital’s Rule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/implicit_differentiation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Implicit Differentiation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/related_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Related rates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../derivatives/taylor_series_polynomials.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Taylor Polynomials and other Approximating Polynomials</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../integrals.html" class="sidebar-item-text sidebar-link">Integrals</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/area.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Area under a curve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/ftc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Fundamental Theorem or Calculus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/substitution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Substitution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/integration_by_parts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Integration By Parts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/partial_fractions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Partial Fractions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/improper_integrals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Improper Integrals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/mean_value_theorem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Mean value theorem for integrals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/area_between_curves.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Area between two curves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/center_of_mass.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Center of Mass</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/volumes_slice.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Volumes by slicing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/arc_length.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Arc length</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integrals/surface_area.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Surface Area</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../ODEs.html" class="sidebar-item-text sidebar-link">ODEs</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ODEs/odes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">ODEs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ODEs/euler.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Euler’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ODEs/solve.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">The problem-algorithm-solve interface</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ODEs/differential_equations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">The <code>DifferentialEquations</code> suite</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../differentiable_vector_calculus.html" class="sidebar-item-text sidebar-link">Differential vector calculus</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/polar_coordinates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Polar Coordinates and Curves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Vectors and matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/vector_valued_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Vector-valued functions, <span class="math inline">\(f:R \rightarrow R^n\)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/scalar_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Scalar functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/scalar_functions_applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Applications with scalar functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/vector_fields.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Functions <span class="math inline">\(R^n \rightarrow R^m\)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../differentiable_vector_calculus/plots_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">2D and 3D plots in Julia with Plots</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../integral_vector_calculus.html" class="sidebar-item-text sidebar-link">Integral vector calculus</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integral_vector_calculus/double_triple_integrals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Multi-dimensional integrals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integral_vector_calculus/line_integrals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Line and Surface Integrals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integral_vector_calculus/div_grad_curl.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">The Gradient, Divergence, and Curl</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integral_vector_calculus/stokes_theorem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Green’s Theorem, Stokes’ Theorem, and the Divergence Theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integral_vector_calculus/review.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Quick Review of Vector Calculus</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../alternatives.html" class="sidebar-item-text sidebar-link">Alternative packages</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../alternatives/symbolics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Symbolics.jl</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../alternatives/SciML.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">The SciML suite of packages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../alternatives/plotly_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">JavaScript based plotting libraries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../alternatives/makie_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Calculus plots with Makie</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">Appendices</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../misc/getting_started_with_julia.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Getting started with Julia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../misc/julia_interfaces.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Julia interfaces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../misc/calculus_with_julia.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">The <code>CalculusWithJulia</code> package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../misc/unicode.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Usages of Unicode symbols</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../misc/quick_notes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Quick introduction to Calculus with Julia</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#solids-of-revolution" id="toc-solids-of-revolution" class="nav-link active" data-scroll-target="#solids-of-revolution"><span class="toc-section-number">45.1</span>  Solids of revolution</a>
  <ul class="collapse">
  <li><a href="#the-washer-method" id="toc-the-washer-method" class="nav-link" data-scroll-target="#the-washer-method"><span class="toc-section-number">45.1.1</span>  The washer method</a></li>
  </ul></li>
  <li><a href="#solids-with-known-cross-section" id="toc-solids-with-known-cross-section" class="nav-link" data-scroll-target="#solids-with-known-cross-section"><span class="toc-section-number">45.2</span>  Solids with known cross section</a>
  <ul class="collapse">
  <li><a href="#cavalieris-method" id="toc-cavalieris-method" class="nav-link" data-scroll-target="#cavalieris-method"><span class="toc-section-number">45.2.1</span>  Cavalieri’s method</a></li>
  </ul></li>
  <li><a href="#the-second-theorem-of-pappus" id="toc-the-second-theorem-of-pappus" class="nav-link" data-scroll-target="#the-second-theorem-of-pappus"><span class="toc-section-number">45.3</span>  The second theorem of Pappus</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions"><span class="toc-section-number">45.4</span>  Questions</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/jverzani/CalculusWithJuliaNotes.jl/edit/main/quarto/integrals/volumes_slice.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/jverzani/CalculusWithJuliaNotes.jl/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Volumes by slicing</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<pre class="{julia}"><code>#| echo: false

import Logging
Logging.disable_logging(Logging.Info) # or e.g. Logging.Info
Logging.disable_logging(Logging.Warn)

import SymPy
function Base.show(io::IO, ::MIME"text/html", x::T) where {T &lt;: SymPy.SymbolicObject}
    println(io, "&lt;span class=\"math-left-align\" style=\"padding-left: 4px; width:0; float:left;\"&gt; ")
    println(io, "\\[")
    println(io, sympy.latex(x))
    println(io, "\\]")
    println(io, "&lt;/span&gt;")
end

# hack to work around issue
import Markdown
import CalculusWithJulia
function CalculusWithJulia.WeaveSupport.ImageFile(d::Symbol, f::AbstractString, caption; kwargs...)
    nm = joinpath("..", string(d), f)
    u = "![$caption]($nm)"
    Markdown.parse(u)
end

nothing</code></pre>
<p>This section uses these add-on packages:</p>
<pre class="{julia}"><code>using CalculusWithJulia
using Plots
using QuadGK
using Unitful, UnitfulUS
using Roots
using SymPy</code></pre>
<pre class="{julia}"><code>#| echo: false
#| results: "hidden"
using CalculusWithJulia.WeaveSupport

import LinearAlgebra: norm

const frontmatter = (
        title = "Volumes by slicing",
        description = "Calculus with Julia: Volumes by slicing",
        tags = ["CalculusWithJulia", "integrals", "volumes by slicing"],
);
nothing</code></pre>
<hr>
<pre class="{julia}"><code>#| hold: true
#| echo: false
imgfile = "figures/michelin-man.jpg"
caption = """

Hey Michelin Man, how much does that costume weigh?

"""
ImageFile(:integrals, imgfile, caption)</code></pre>
<p>An ad for a summer job says work as the Michelin Man! Sounds promising, but how much will that costume weigh? A very hot summer may make walking around in a heavy costume quite uncomfortable.</p>
<p>A back-of-the envelope calculation would start by</p>
<ul>
<li>Mentally separating out each “tire” and lining them up one by one.</li>
<li>Counting the number of “tires” (or rings), say <span class="math inline">\(n\)</span>.</li>
<li>Estimating the radius for each tire, say <span class="math inline">\(r_i\)</span> for <span class="math inline">\(1 \leq i \leq n\)</span>.</li>
<li>Estimating the height for each tire, say <span class="math inline">\(h_i\)</span> for <span class="math inline">\(1 \leq i \leq n\)</span></li>
</ul>
<p>Then the volume would be found by adding:</p>
<p><span class="math display">\[
V = \pi \cdot r_1^2 \cdot h_1 + \pi \cdot r_2^2 \cdot h_2 + \cdot + \pi \cdot r_n^2 \cdot h_n.
\]</span></p>
<p>The weight would come by multiplying the volume by some appropriate density.</p>
<p>Looking at the sum though, we see the makings of an approximate integral. If the heights were to get infinitely small, we might expect this to approach something like <span class="math inline">\(V=\int_a^b \pi r(h)^2 dh\)</span>.</p>
<p>In fact, we have in general:</p>
<blockquote class="blockquote">
<p><strong>Volume of a figure with a known cross section</strong>: The volume of a solid with known cross-sectional area <span class="math inline">\(A_{xc}(x)\)</span> from <span class="math inline">\(x=a\)</span> to <span class="math inline">\(x=b\)</span> is given by</p>
<p><span class="math inline">\(V = \int_a^b A_{xc}(x) dx.\)</span></p>
<p>This assumes <span class="math inline">\(A_{xc}(x)\)</span> is integrable.</p>
</blockquote>
<p>This formula is derived by approximating the volume by “slabs” with volume <span class="math inline">\(A_{xc}(x) \Delta x\)</span> and using the Riemann integral’s definition to pass to the limit. The discs of the Michelin man are an example, where the cross-sectional area is just that of a circle, or <span class="math inline">\(\pi r^2\)</span>.</p>
<section id="solids-of-revolution" class="level2" data-number="45.1">
<h2 data-number="45.1" class="anchored" data-anchor-id="solids-of-revolution"><span class="header-section-number">45.1</span> Solids of revolution</h2>
<p>We begin with some examples of a special class of solids - solids of revolution. These have an axis of symmetry from which the slabs are then just circular disks.</p>
<p>Consider the volume contained in this glass, it will depend on the radius at different values of <span class="math inline">\(x\)</span>:</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
imgfile = "figures/integration-glass.jpg"
caption = L"""

A wine glass oriented so that it is seen as generated by revolving a
curve about the $x$ axis. The radius of revolution varies as a function of $x$
between about $0$ and $6.2$cm.

"""
ImageFile(:integrals, imgfile, caption)</code></pre>
<p>If <span class="math inline">\(r(x)\)</span> is the radius as a function of <span class="math inline">\(x\)</span>, then the cross sectional area is <span class="math inline">\(\pi r(x)^2\)</span> so the volume is given by:</p>
<p><span class="math display">\[
V = \int_a^b \pi r(x)^2 dx.
\]</span></p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The formula is for a rotation around the <span class="math inline">\(x\)</span>-axis, but can easily be generalized to rotating around any line (say the <span class="math inline">\(y\)</span>-axis or <span class="math inline">\(y=x\)</span>, …) just by adjusting what <span class="math inline">\(r(x)\)</span> is taken to be.</p>
</div>
</div>
<p>For a numeric example, we consider the original Red <a href="http://en.wikipedia.org/wiki/Red_Solo_Cup">Solo</a> Cup. The dimensions of the cup were basically: a top diameter of <span class="math inline">\(d_1 = 3~ \frac{3}{4}\)</span> inches, a bottom diameter of <span class="math inline">\(d_0 = 2~ \frac{1}{2}\)</span> inches and a height of <span class="math inline">\(h = 4~ \frac{3}{4}\)</span> inches.</p>
<p>The central axis is straight down. If we rotate the cup so this is the <span class="math inline">\(x\)</span>-axis, then we can get</p>
<p><span class="math display">\[
r(x) = \frac{d_0}{2} + \frac{d_1/2 - d_0/2}{h}x = \frac{5}{4} + \frac{5}{38}x
\]</span></p>
<p>The volume in cubic inches will be:</p>
<p><span class="math display">\[
V = \int_0^h \pi r(x)^2 dx
\]</span></p>
<p>This is</p>
<pre class="{julia}"><code>d0, d1, h = 2.5, 3.75, 4.75
rad(x) = d0/2 + (d1/2 - d0/2)/h * x
vol, _ = quadgk(x -&gt; pi * rad(x)^2, 0, h)</code></pre>
<p>So <span class="math inline">\(36.9 \text{in}^3\)</span>. How many ounces is that? It is useful to know that 1 <a href="http://en.wikipedia.org/wiki/Gallon">gallon</a> of water is defined as <span class="math inline">\(231\)</span> cubic inches, contains <span class="math inline">\(128\)</span> ounces, and weighs <span class="math inline">\(8.34\)</span> pounds.</p>
<p>So our cup holds this many ounces:</p>
<pre class="{julia}"><code>ozs = vol / 231 * 128</code></pre>
<p>Full it is about <span class="math inline">\(20\)</span> ounces, though this doesn’t really account for the volume taken up by the bottom of the cup, etc.</p>
<p>If you are poor with units, <code>Julia</code> can provide some help through the <code>Unitful</code> package. Here the additional <code>UnitfulUS</code> package must also be included, as was done above, to access fluid ounces:</p>
<pre class="{julia}"><code>vol * u"inch"^3 |&gt; us"floz"</code></pre>
<p>Before Solo “squared” the cup, the Solo cup had markings that - <a href="http://www.snopes.com/food/prepare/solocups.asp">some thought</a> - indicated certain volume amounts.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
imgfile = "figures/red-solo-cup.jpg"
caption = "Markings on the red Solo cup indicated various volumes"
ImageFile(:integrals, imgfile, caption)</code></pre>
<p>What is the height for <span class="math inline">\(5\)</span> ounces (for a glass of wine)? <span class="math inline">\(12\)</span> ounces (for a beer unit)?</p>
<p>Here the volume is fixed, but the height is not. For <span class="math inline">\(v\)</span> ounces, we need to convert to cubic inches. The conversion is <span class="math inline">\(1\)</span> ounce is <span class="math inline">\(231/128 \text{in}^3\)</span>.</p>
<p>So we need to solve <span class="math inline">\(v \cdot (231/128) = \int_0^h\pi r(x)^2 dx\)</span> for <span class="math inline">\(h\)</span> when <span class="math inline">\(v=5\)</span> and <span class="math inline">\(v=12\)</span>.</p>
<p>Let’s express volume as a function of <span class="math inline">\(h\)</span>:</p>
<pre class="{julia}"><code>Vol(h) = quadgk(x -&gt; pi * rad(x)^2, 0, h)[1]</code></pre>
<p>Then to solve we have:</p>
<pre class="{julia}"><code>v₅ = 5
h5 = find_zero(h -&gt; Vol(h) - v₅ * 231 / 128, 4)</code></pre>
<p>and</p>
<pre class="{julia}"><code>v₁₂ = 12
h12 = find_zero(h -&gt; Vol(h) - v₁₂ * 231 / 128, 4)</code></pre>
<p>As a percentage of the total height, these are:</p>
<pre class="{julia}"><code>h5/h, h12/h</code></pre>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Were performance at issue, Newton’s method might also have been considered here, as the derivative is easily computed by the fundamental theorem of calculus.</p>
</div>
</div>
<section id="example" class="level5">
<h5 class="anchored" data-anchor-id="example">Example</h5>
<p>By rotating the line segment <span class="math inline">\(x/r + y/h=1\)</span> that sits in the first quadrant around the <span class="math inline">\(y\)</span> axis, we will generate a right-circular cone. The volume of which can be expressed through the above formula by noting the radius, as a function of <span class="math inline">\(y\)</span>, will be <span class="math inline">\(R = r(1 - y/h)\)</span>. This gives the well-known volume of a cone:</p>
<pre class="{julia}"><code>#| hold: true
@syms r h x y
R = r*(1 - y/h)
integrate(pi*R^2, (y, 0, h))</code></pre>
<p>The frustum of a cone is simply viewed as a cone with its top cut off. If the original height would have been <span class="math inline">\(h_0\)</span> and the actual height <span class="math inline">\(h_1\)</span>, then the volume remaining is just <span class="math inline">\(\int_{h_0}^h \pi r(y)^2 dy = \pi h_1 r^2/3 - \pi h_0 r^2/3 = \pi r^2 (h_1-h_0)/3\)</span>.</p>
<p>It is not unusual to parameterize a cone by the angle <span class="math inline">\(\theta\)</span> it makes and the height. Since <span class="math inline">\(r/h=\tan\theta\)</span>, this gives the formula <span class="math inline">\(V = \pi/3\cdot h^3\tan(\theta)^2\)</span>.</p>
</section>
<section id="example-1" class="level5">
<h5 class="anchored" data-anchor-id="example-1">Example</h5>
<p><a href="http://tinyurl.com/8a6ygv">Gabriel’s</a> horn is a geometric figure of mathematics - but not the real world - which has infinite height, but not volume! The figure is found by rotating the curve <span class="math inline">\(y=1/x\)</span> around the <span class="math inline">\(x\)</span> axis from <span class="math inline">\(1\)</span> to <span class="math inline">\(\infty\)</span>. If the volume formula holds, what is the volume of this “horn?”</p>
<pre class="{julia}"><code>radius(x) = 1/x
quadgk(x -&gt; pi*radius(x)^2, 1, Inf)[1]</code></pre>
<p>That is a value very reminiscent of <span class="math inline">\(\pi\)</span>, which it is as <span class="math inline">\(\int_1^\infty 1/x^2 dx = -1/x\big|_1^\infty=1\)</span>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The interest in this figure is that soon we will be able to show that it has <strong>infinite</strong> surface area, leading to the <a href="http://tinyurl.com/osawwqm">paradox</a> that it seems possible to fill it with paint, but not paint the outside.</p>
</div>
</div>
</section>
<section id="example-2" class="level5">
<h5 class="anchored" data-anchor-id="example-2">Example</h5>
<p>A movie studio hand is asked to find a prop vase to be used as a <a href="http://en.wikipedia.org/wiki/Chinese_ceramics">Ming vase</a> in an upcoming scene. The dimensions specified are for the outside diameter in centimeters and are given by</p>
<p><span class="math display">\[
d(h) = \begin{cases}
2 \sqrt{26^2 - (h-20)^2} &amp; 0 \leq h \leq 44\\
20 \cdot e^{-(h - 44)/10} &amp; 44 &lt; h \leq 50.
\end{cases}
\]</span></p>
<p>If the vase were solid, what would be the volume?</p>
<p>We define <code>d</code> using a ternary operator to handle the two cases:</p>
<pre class="{julia}"><code>d(h) = h &lt;= 44 ? 2*sqrt(26^2 - (h-20)^2) : 20 * exp(-(h-44)/10)
rad(h) = d(h)/2</code></pre>
<p>The volume in cm<span class="math inline">\(^3\)</span> is then:</p>
<pre class="{julia}"><code>Vₜ, _ = quadgk(h -&gt; pi * rad(h)^2, 0, 50)</code></pre>
<p>For the actual shoot, the vase is to be filled with ash, to simulate a funeral urn. (It will then be knocked over in a humorous manner, of course.) How much ash is needed if the vase has walls that are 1/2 centimeter thick</p>
<p>We need to subtract <span class="math inline">\(0.5\)</span> from the radius and <code>a</code> then recompute:</p>
<pre class="{julia}"><code>V_int, _ = quadgk(h -&gt; pi * (rad(h) - 1/2)^2, 1/2, 50)</code></pre>
<p>A liter of volume is <span class="math inline">\(1000 \text{cm}^3\)</span>. So this is about <span class="math inline">\(68\)</span> liters, or more than 15 gallons. Perhaps the dimensions given were bit off.</p>
<p>While we are here, to compute the actual volume of the material in the vase could be done by subtraction.</p>
<pre class="{julia}"><code>Vₜ - V_int</code></pre>
</section>
<section id="the-washer-method" class="level3" data-number="45.1.1">
<h3 data-number="45.1.1" class="anchored" data-anchor-id="the-washer-method"><span class="header-section-number">45.1.1</span> The washer method</h3>
<p>Returning to the Michelin Man, in our initial back-of-the-envelope calculation we didn’t account for the fact that a tire isn’t a disc, as it has its center cut out. Returning, suppose <span class="math inline">\(R_i\)</span> is the outer radius and <span class="math inline">\(r_i\)</span> the inner radius. Then each tire has volume</p>
<p><span class="math display">\[
\pi R_i^2 h_i - \pi r_i^2 h_i = \pi (R_i^2 - r_i^2) h_i.
\]</span></p>
<p>Rather than use <span class="math inline">\(\pi r(x)^2\)</span> for a cross section, we would use <span class="math inline">\(\pi (R(x)^2 - r(x)^2)\)</span>.</p>
<p>In general we call a shape like the tire a “washer” and use this formula for a washer’s cross section <span class="math inline">\(A_{xc}(x) = \pi(R(x)^2 - r(x)^2)\)</span>.</p>
<p>Then the volume for the solid of revolution whose cross sections are washers would be:</p>
<p><span class="math display">\[
V = \int_a^b \pi \cdot (R(x)^2 - r(x)^2) dx.
\]</span></p>
<section id="example-3" class="level5">
<h5 class="anchored" data-anchor-id="example-3">Example</h5>
<p>An artist is working with a half-sphere of material, and wishes to bore out a conical shape. What would be the resulting volume, if the two figures are modeled by</p>
<p><span class="math display">\[
R(x) = \sqrt{1^2 - (x-1)^2}, \quad r(x) = x,
\]</span></p>
<p>with <span class="math inline">\(x\)</span> ranging from <span class="math inline">\(x=0\)</span> to <span class="math inline">\(1\)</span>?</p>
<p>The answer comes by integrating:</p>
<pre class="{julia}"><code>#| hold: true
Rad(x) = sqrt(1 - (x-1)^2)
rad(x) = x
V, _ = quadgk(x -&gt; pi*(Rad(x)^2 - rad(x)^2), 0, 1)</code></pre>
</section>
</section>
</section>
<section id="solids-with-known-cross-section" class="level2" data-number="45.2">
<h2 data-number="45.2" class="anchored" data-anchor-id="solids-with-known-cross-section"><span class="header-section-number">45.2</span> Solids with known cross section</h2>
<p>The Dart cup company now produces the red solo cup with a <a href="http://www.solocup.com/products/squared-plastic-cup/">square</a> cross section. Suppose the dimensions are the same: a top diameter of <span class="math inline">\(d_1 = 3 3/4\)</span> inches, a bottom diameter of <span class="math inline">\(d_0 = 2 1/2\)</span> inches and a height of <span class="math inline">\(h = 4 3/4\)</span> inches. What is the volume now?</p>
<p>The difference, of course, is that cross sections now have area <span class="math inline">\(d^2\)</span>, as opposed to <span class="math inline">\(\pi r^2\)</span>. This leads to some difference, which we quantify, as follows:</p>
<pre class="{julia}"><code>#| hold: true
d0, d1, h = 2.5, 3.75, 4.75
d(x) = d0 + (d1 - d0)/h * x
vol, _ = quadgk(x -&gt; d(x)^2, 0, h)
vol / 231 * 128</code></pre>
<p>This shape would have more volume - the cross sections are bigger. Presumably the dimensions have changed. Without going out and buying a cup, let’s assume the cross-sectional diameter remained the same, not the diameter. This means the largest dimension is the same. The cross section diameter is <span class="math inline">\(\sqrt{2}\)</span> larger. What would this do to the area?</p>
<p>We could do this two ways: divide <span class="math inline">\(d_0\)</span> and <span class="math inline">\(d_1\)</span> by <span class="math inline">\(\sqrt{2}\)</span> and recompute. However, each cross section of this narrower cup would simply be <span class="math inline">\(\sqrt{2}^2\)</span> smaller, so the total volume would change by <span class="math inline">\(2\)</span>, or be 13 ounces. We have <span class="math inline">\(26.04\)</span> is too big, and <span class="math inline">\(13.02\)</span> is too small, so some other overall dimensions are used.</p>
<section id="example-4" class="level5">
<h5 class="anchored" data-anchor-id="example-4">Example</h5>
<p>For a general cone, we use this <a href="http://en.wikipedia.org/wiki/Cone">definition</a>:</p>
<blockquote class="blockquote">
<p>A cone is the solid figure bounded by a base in a plane and by a surface (called the lateral surface) formed by the locus of all straight line segments joining the apex to the perimeter of the base.</p>
</blockquote>
<p>Let <span class="math inline">\(h\)</span> be the distance from the apex to the base. Consider cones with the property that all planes parallel to the base intersect the cone with the same shape, though perhaps a different scale. This figure shows an example, with the rays coming from the apex defining the volume.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
h = 5
R, r, rho = 1, 1/4, 1/4
f(t) = (R-r) * cos(t) + rho * cos((R-r)/r * t)
g(t) = (R-r) * sin(t) - rho * sin((R-r)/r * t)
ts = range(0, 2pi, length=100)

p = plot(f.(ts), g.(ts), zero.(ts), legend=false)
for t ∈ range(0, 2pi, length=25)
    plot!(p, [0,f(t)], [0,g(t)], [h, 0], linecolor=:red)
end
p</code></pre>
<p>A right circular cone is one where this shape is a circle. This definition can be more general, as a square-based right pyramid is also such a cone. After possibly reorienting the cone in space so the base is at <span class="math inline">\(u=0\)</span> and the apex at <span class="math inline">\(u=h\)</span> the volume of the cone can be found from:</p>
<p><span class="math display">\[
V = \int_0^h A_{xc}(u) du.
\]</span></p>
<p>The cross sectional area <span class="math inline">\(A_{xc}(u)\)</span> satisfies a formula in terms of <span class="math inline">\(A_{xc}(0)\)</span>, the area of the base:</p>
<p><span class="math display">\[
A_{xc}(u)  = A_{xc}(0) \cdot (1 - \frac{u}{h})^2
\]</span></p>
<p>So the integral becomes:</p>
<p><span class="math display">\[
V = \int_0^h A_{xc}(u) du = A_{xc}(0) \int_0^h (1 - \frac{u}{h})^2 du = A_{xc}(0) \int_0^1 v^2 \frac{1}{h} dv = A_{xc}(0) \frac{h}{3}.
\]</span></p>
<p>This gives a general formula for the volume of such cones.</p>
</section>
<section id="cavalieris-method" class="level3" data-number="45.2.1">
<h3 data-number="45.2.1" class="anchored" data-anchor-id="cavalieris-method"><span class="header-section-number">45.2.1</span> Cavalieri’s method</h3>
<p><a href="http://tinyurl.com/oda9xd9">Cavalieri’s</a> Principle is “Suppose two regions in three-space (solids) are included between two parallel planes. If every plane parallel to these two planes intersects both regions in cross-sections of equal area, then the two regions have equal volumes.” (Wikipedia).</p>
<p>With the formula for the volume of solids based on cross sections, this is a trivial observation, as the functions giving the cross-sectional area are identical. Still, it can be surprising. Consider a sphere with an interior cylinder bored out of it. (The <a href="http://tinyurl.com/o237v83">Napkin</a> ring problem.) The bore has height <span class="math inline">\(h\)</span> - for larger radius spheres this means very wide bores.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
#The following illustrates $R=5$ and $h=8$.

R =5; h1 = 2*4

theta = asin(h1/2/R)
thetas = range(-theta, stop=theta, length=100)
ts = range(-pi, stop=pi, length=100)
y = h1/4

p = plot(legend=false, aspect_ratio=:equal);
plot!(p, R*cos.(ts), R*sin.(ts));
plot!(p, R*cos.(thetas), R*sin.(thetas), color=:orange);

plot!(p, [R*cos.(theta), R*cos.(theta)], [h1/2, -h1/2], color=:orange);
plot!(p, [R*cos.(theta), sqrt(R^2 - y^2)], [y, y], color=:orange)

plot!(p, [0, R*cos.(theta)], [0,0], color=:red);
plot!(p,[ 0, R*cos.(theta)], [0,h1/2], color=:red);

annotate!(p, [(.5, -2/3, "sqrt(R²- (h/2)²)"),
              (R*cos.(theta)-.6, h1/4, "h/2"),
              (1.5, 1.75*tan.(theta), "R")])

p
</code></pre>
<p>The small orange line is rotated, so using the washer method we get the cross sections given by <span class="math inline">\(\pi(r_0^2 - r_i^2)\)</span>, the outer and inner radii, as a function of <span class="math inline">\(y\)</span>.</p>
<p>The outer radii has points <span class="math inline">\((x,y)\)</span> satisfying <span class="math inline">\(x^2 + y^2 = R^2\)</span>, so is <span class="math inline">\(\sqrt{R^2 - y^2}\)</span>. The inner radii has a constant value, and as indicated in the figure, is <span class="math inline">\(\sqrt{R^2 - (h/2)^2}\)</span>, by the Pythagorean theorem.</p>
<p>Thus the cross sectional area is</p>
<p><span class="math display">\[
\pi( (\sqrt{R^2 - y^2})^2 - (\sqrt{R^2 - (h/2)^2})^2 )
= \pi ((R^2 - y^2) - (R^2 - (h/2)^2))
= \pi ((\frac{h}{2})^2 - y^2)
\]</span></p>
<p>As this does not depend on <span class="math inline">\(R\)</span>, and the limits of integration would always be <span class="math inline">\(-h/2\)</span> to <span class="math inline">\(h/2\)</span> by Cavalieri’s principle, the volume of the solid will be independent of <span class="math inline">\(R\)</span> too.</p>
<p>To actually compute this volume, we take <span class="math inline">\(R=h/2\)</span>, so that the bore hole is just a line of no volume, the resulting volume is then that of a sphere with radius <span class="math inline">\(h/2\)</span>, or <span class="math inline">\(4/3\pi(h/2)^3 = \pi h^3/6\)</span>.</p>
</section>
</section>
<section id="the-second-theorem-of-pappus" class="level2" data-number="45.3">
<h2 data-number="45.3" class="anchored" data-anchor-id="the-second-theorem-of-pappus"><span class="header-section-number">45.3</span> The second theorem of Pappus</h2>
<p>The second theorem of <a href="http://tinyurl.com/l43vw4">Pappus</a> says that if a plane figure <span class="math inline">\(F\)</span> is rotated around an axis to form a solid of revolution, the total volume can be written as <span class="math inline">\(2\pi r A(F)\)</span>, where <span class="math inline">\(r\)</span> is the distance the centroid is from the axis of revolution, and <span class="math inline">\(A(F)\)</span> is the area of the plane figure. In short, the distance traveled by the centroid times the area.</p>
<p>This can make some computations trivial. For example, we can make a torus (or donut) by rotating the circle <span class="math inline">\((x-2)^2 + y^2 = 1\)</span> about the <span class="math inline">\(y\)</span> axis. As the centroid is clearly <span class="math inline">\((2, 0)\)</span>, with <span class="math inline">\(r=2\)</span> in the above formula, and the area of the circle is <span class="math inline">\(\pi 1^2\)</span>, the volume of the donut is <span class="math inline">\(2\pi(2)(\pi) = 4\pi^2\)</span>.</p>
<section id="example-5" class="level5">
<h5 class="anchored" data-anchor-id="example-5">Example</h5>
<p>Above, we found the volume of a cone, as it is a solid of revolution, through the general formula. However, parameterizing the cone as the revolution of a triangle with vertices <span class="math inline">\((0,0)\)</span>, <span class="math inline">\((r, 0)\)</span>, and <span class="math inline">\((0,h)\)</span> and using the formula for the center of mass in the <span class="math inline">\(x\)</span> direction of such a triangle, <span class="math inline">\(r/3\)</span>, we get that the volume of a cone with height <span class="math inline">\(h\)</span> and radius <span class="math inline">\(r\)</span> is <span class="math inline">\(2\pi (r/3)\cdot (rh/2) = \pi r^2 h/3\)</span>, in agreement with the calculus based computation.</p>
</section>
</section>
<section id="questions" class="level2" data-number="45.4">
<h2 data-number="45.4" class="anchored" data-anchor-id="questions"><span class="header-section-number">45.4</span> Questions</h2>
<section id="question" class="level6">
<h6 class="anchored" data-anchor-id="question">Question</h6>
<p>Consider this big Solo cup:</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
imgfile ="figures/big-solo-cup.jpg"
caption = " Big solo cup. "
ImageFile(:integrals, imgfile, caption)</code></pre>
<p>It has approximate dimensions: smaller radius 5 feet, upper radius 8 feet and height 15 feet. How many gallons is it? At <span class="math inline">\(8\)</span> pounds a gallon this would be pretty heavy!</p>
<p>Two facts are useful:</p>
<ul>
<li>a cubic foot is 7.48052 gallons</li>
<li>the radius as a function of height is <span class="math inline">\(r(h) = 5 + (3/15)\cdot h\)</span></li>
</ul>
<pre class="{julia}"><code>#| hold: true
#| echo: false
gft = 7.48052
rad(h) = 5 + (3/15)*h
a,err = quadgk(h -&gt; pi*rad(h)^2, 0, 15)
val = a*gft
numericq(val, 1e1)</code></pre>
</section>
<section id="question-1" class="level6">
<h6 class="anchored" data-anchor-id="question-1">Question</h6>
<p>In <em>Glass Shape Influences Consumption Rate</em> for Alcoholic <a href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0043007">Beverages</a> the authors demonstrate that the shape of the glass can have an effect on the rate of consumption, presumably people drink faster when they aren’t sure how much they have left. In particular, they comment that people have difficulty judging the half-finished-by-volume mark.</p>
<p>This figure shows some of the wide variety of beer-serving glasses:</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
imgfile ="figures/beer_glasses.jpg"
caption = "A variety of different serving glasses for beer."
ImageFile(:integrals, imgfile, caption)</code></pre>
<p>We work with metric units, as there is a natural relation between volume in cm<span class="math inline">\(^3\)</span> and liquid measure (<span class="math inline">\(1\)</span> liter = <span class="math inline">\(1000\)</span> cm<span class="math inline">\(^3\)</span>, so a <span class="math inline">\(16\)</span>-oz pint glass is roughly <span class="math inline">\(450\)</span> cm<span class="math inline">\(^3\)</span>.)</p>
<p>Let two glasses be given as follows. A typical pint glass with linearly increasing radius:</p>
<p><span class="math display">\[
r(h) = 3 + \frac{1}{5}h, \quad 0 \leq h \leq b;
\]</span></p>
<p>and a curved-edge one:</p>
<p><span class="math display">\[
s(h) = 3 + \log(1 + h), \quad 0 \leq h \leq b
\]</span></p>
<p>The following functions find the volume as a function of height, <span class="math inline">\(h\)</span>:</p>
<pre class="{julia}"><code>r1(h) = 3 + h/5
s1(h) = 2 + log(1 + h)
r_vol(h) = quadgk(x -&gt; pi*r1(x)^2, 0, h)[1]
s_vol(h) = quadgk(x -&gt; pi*s1(x)^2, 0, h)[1]</code></pre>
<ul>
<li>For the straight-sided glass find <span class="math inline">\(h\)</span> so that the volume is <span class="math inline">\(450\)</span>.</li>
</ul>
<pre class="{julia}"><code>#| echo: false
h450 = find_zero(h -&gt; r_vol(h) - 450, 10)
numericq(h450)</code></pre>
<ul>
<li>For the straight-sided glass find <span class="math inline">\(h\)</span> so that the volume is <span class="math inline">\(225\)</span> (half full).</li>
</ul>
<pre class="{julia}"><code>#| echo: false
h225 = find_zero(h -&gt; r_vol(h) - 225, 10)
numericq(h225)</code></pre>
<ul>
<li>For the straight-sided glass, what is the percentage of the total height when the glass is half full. (For a cylinder it would just be 50.</li>
</ul>
<pre class="{julia}"><code>#| echo: false
numericq(h225/450 * 100, 2, units="percent")</code></pre>
<ul>
<li>People often confuse the half-way by height amount for the half way by volume, as it is for the cylinder. Take the height for the straight-sided glass filled with <span class="math inline">\(450\)</span> mm, divide it by <span class="math inline">\(2\)</span>, then compute the percentage of volume at the half way height to the original.</li>
</ul>
<pre class="{julia}"><code>#| echo: false
numericq(r_vol(h450/2)/450*100, 2, units="percent")</code></pre>
<hr>
<ul>
<li>For the curved-sided glass find <span class="math inline">\(h\)</span> so that the volume is <span class="math inline">\(450\)</span>.</li>
</ul>
<pre class="{julia}"><code>#| echo: false
h_450 = find_zero(h -&gt; s_vol(h) - 450, 10)
numericq(h_450)</code></pre>
<ul>
<li>For the curved-sided glass find <span class="math inline">\(h\)</span> so that the volume is <span class="math inline">\(225\)</span> (half full).</li>
</ul>
<pre class="{julia}"><code>#| echo: false
h_225 = find_zero(h -&gt; s_vol(h) - 225, 10)
numericq(h_225)</code></pre>
<ul>
<li>For the curved-sided glass, what is the percentage of the total height when the glass is half full. (For a cylinder it would just be 50.</li>
</ul>
<pre class="{julia}"><code>#| echo: false
numericq(h_225/450 * 100, 2, units="percent")</code></pre>
<ul>
<li>People often confuse the half-way by height amount for the half way by volume, as it is for the cylinder. Take the height for the curved-sided glass filled with <span class="math inline">\(450\)</span> mm, divide it by <span class="math inline">\(2\)</span>, then compute the percentage of volume at the half way height to the original.</li>
</ul>
<pre class="{julia}"><code>#| echo: false
numericq(s_vol(h_450/2)/450*100, 2, units="percent")</code></pre>
</section>
<section id="question-2" class="level6">
<h6 class="anchored" data-anchor-id="question-2">Question</h6>
<p>A right <a href="http://en.wikipedia.org/wiki/Pyramid_%28geometry%29">pyramid</a> has its apex (top point) above the centroid of its base, and for our purposes, each of its cross sections. Suppose a pyramid has square base of dimension <span class="math inline">\(w\)</span> and height of dimension <span class="math inline">\(h\)</span>.</p>
<p>Will this integral give the volume:</p>
<p><span class="math display">\[
V = \int_0^h w^2 (1 - \frac{y}{h})^2 dy?
\]</span></p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
yesnoq("yes")</code></pre>
<p>What is the volume?</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
choices = [
"``1/3 \\cdot b\\cdot h``",
"``1/3 \\cdot w^2\\cdot h``",
"``l\\cdot w \\cdot h/ 3``"
]
answ = 2
radioq(choices, answ)</code></pre>
</section>
<section id="question-3" class="level6">
<h6 class="anchored" data-anchor-id="question-3">Question</h6>
<p>An ellipsoid is formed by rotating the region in the first and second quadrants bounded by the ellipse <span class="math inline">\((x/2)^2 + (y/3)^2=1\)</span> and the <span class="math inline">\(x\)</span> axis around the <span class="math inline">\(x\)</span> axis. What is the volume of this ellipsoid? Find it numerically.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
f(x) = 3*sqrt( 1 - (x/2)^2 )
val, _ = quadgk(x -&gt; pi * f(x)^2, -2, 2)
numericq(val)</code></pre>
</section>
<section id="question-4" class="level6">
<h6 class="anchored" data-anchor-id="question-4">Question</h6>
<p>An ellipsoid is formed by rotating the region in the first and second quadrants bounded by the ellipse <span class="math inline">\((x/a)^2 + (y/b)^2=1\)</span> and the <span class="math inline">\(x\)</span> axis around the <span class="math inline">\(x\)</span> axis. What is the volume of this ellipsoid? Find it symbolically.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
choices = [
"``4/3 \\cdot \\pi a b^2``",
"``4/3 \\cdot \\pi a^2 b``",
"``\\pi/3 \\cdot a b^2``"
]
answ = 1
radioq(choices, answ)</code></pre>
</section>
<section id="question-5" class="level6">
<h6 class="anchored" data-anchor-id="question-5">Question</h6>
<p>A solid is generated by rotating the region enclosed by the graph <span class="math inline">\(y=\sqrt{x}\)</span>, the lines <span class="math inline">\(x=1\)</span>, <span class="math inline">\(x=2\)</span>, and <span class="math inline">\(y=1\)</span> about the <span class="math inline">\(x\)</span> axis. Find the volume of the solid.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
Ra(x) = sqrt(x)
ra(x) = 1
a,b=1,2
val, _ = quadgk(x -&gt; pi * (Ra(x)^2 - ra(x)^2), a,b)
numericq(val)</code></pre>
</section>
<section id="question-6" class="level6">
<h6 class="anchored" data-anchor-id="question-6">Question</h6>
<p>The region enclosed by the graphs of <span class="math inline">\(y=x^3 - 1\)</span> and <span class="math inline">\(y=x-1\)</span> are rotated around the <span class="math inline">\(y\)</span> axis. What is the volume of the solid?</p>
<pre class="{julia}"><code>#| hold: true
@syms x
plot(x^3 - 1, 0, 1, legend=false)
plot!(x-1)</code></pre>
<pre class="{julia}"><code>#| hold: true
#| echo: false
Ra(y) = cbrt(y+1)
ra(y) = y + 1
a,b = 0, 1
val, _ = quadgk(x -&gt; pi * (Ra(x)^2 - ra(x)^2), a,b)
numericq(val)</code></pre>
</section>
<section id="question-7" class="level6">
<h6 class="anchored" data-anchor-id="question-7">Question</h6>
<p>Rotate the region bounded by <span class="math inline">\(y=e^x\)</span>, the line <span class="math inline">\(x=\log(2)\)</span> and the first quadrant about the line <span class="math inline">\(x=\log(2)\)</span>.</p>
<p>(Be careful, the radius in the formula <span class="math inline">\(V=\int_a^b \pi r(u)^2 du\)</span> is from the line <span class="math inline">\(x=\log(2)\)</span>.)</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
a, b = 0, exp(log(2))
ra(y) = log(2) - log(y)
val, _ = quadgk(y -&gt; pi * ra(y)^2, a, b)
numericq(val)</code></pre>
</section>
<section id="question-8" class="level6">
<h6 class="anchored" data-anchor-id="question-8">Question</h6>
<p>Find the volume of rotating the region bounded by the line <span class="math inline">\(y=x\)</span>, <span class="math inline">\(x=1\)</span> and the <span class="math inline">\(x\)</span>-axis around the line <span class="math inline">\(y=x\)</span>. (The Theorem of Pappus is convenient and the fact that the centroid of the triangular region lies at <span class="math inline">\((2/3, 1/3)\)</span>.)</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
cm=[2/3, 1/3]
c = [1/2, 1/2]
rr = norm(cm - c)
A = 1/2 * 1 * 1
val = 2pi * rr * A
numericq(val)</code></pre>
</section>
<section id="question-9" class="level6">
<h6 class="anchored" data-anchor-id="question-9">Question</h6>
<p>Rotate the region bounded by the line <span class="math inline">\(y=x\)</span> and the function <span class="math inline">\(f(x) = x^2\)</span> about the line <span class="math inline">\(y=x\)</span>. What is the resulting volume?</p>
<p>You can integrate in the length along the line <span class="math inline">\(y=x\)</span> (<span class="math inline">\(u\)</span> from <span class="math inline">\(0\)</span> to <span class="math inline">\(\sqrt{2}\)</span>). The radius then can be found by intersecting the line perpendicular line to <span class="math inline">\(y=x\)</span> at <span class="math inline">\(u\)</span> to the curve <span class="math inline">\(f(x)\)</span>. This will do so:</p>
<pre class="{julia}"><code>theta = pi/4  ## we write y=x as y = x * tan(pi/4) for more generality, as this allows other slants.

f(x) = x^2
𝒙(u) = find_zero(x -&gt; u*sin(theta) - 1/tan(theta) * (x - u*cos(theta)) - f(x), (u*cos(theta), 1))
𝒓(u) = sqrt((u*cos(theta) - 𝒙(u))^2 + (u*sin(theta) - f(𝒙(u)))^2)</code></pre>
<p>(Though in this case you can also find <code>r(u)</code> using the quadratic formula.)</p>
<p>With this, find the volume.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
a, b = 0, sqrt(2)
val, _ = quadgk(u -&gt; pi*𝒓(u)^2, a, b)
numericq(val)</code></pre>
<hr>
<p>Repeat (find the volume) only this time with the function <span class="math inline">\(f(x) = x^{20}\)</span>.</p>
<pre class="{julia}"><code>#| hold: true
#| echo: false
a, b = 0, sqrt(2)
f(x) = x^20
xval(u) = find_zero(x -&gt; u*sin(theta) - 1/tan(theta) * (x - u*cos(theta)) - f(x), (0,sqrt(2)))
rad(u) = sqrt((u*cos(theta) - xval(u))^2 + (u*sin(theta) - f(xval(u)))^2)
val, _ = quadgk(u -&gt; pi*rad(u)^2, a, b)
numericq(val)</code></pre>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../integrals/center_of_mass.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Center of Mass</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../integrals/arc_length.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Arc length</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center">Copyright 2022, John Verzani</div>
  </div>
</footer>



</body></html>